### ISSUE TITLE
cal_W

### ISSUE THREAD

**Issue by xingzhewujiangboboniao** [GrokCV/SDD#5]
I am very interested in your research work and glad that you can open source this code. In the process of testing, however, I found that the cal_W function seems to be missing from the code.

**Comment by hellozf1990** [comment]
Thank you very much for your praise and support of our work. We would like to know which weight function you are referring to the cal_W function? In our algorithm, there are three weight functions involved, one for updating variable S and the others for updating two mixed sparse constraints Z1 and Z2. Furthermore, the weighted weights used for updating Z2 are given in the Thres_21() subfunction.

**Comment by ImageVisioner** [comment]
应该是structure_tensor_lambda函数的cal_W函数 ，我这里也无法正常运行

**Comment by hellozf1990** [comment]
您好，我这边看了一下我们的代码，您说的这个问题我们这里能够正常运行，您能把您的报错信息展示一下吗？或者您加我微信15050556266

**Comment by xingzhewujiangboboniao** [comment]
Code error information is as follows:
函数或变量 'cal_W' 无法识别。
出错 structure_tensor_lambda (line 12)
W=cal_W(u,t,f,h1,h2,selfsim);
出错 IRDS_code (line 36)
   [lambda1, lambda2] = structure_tensor_lambda(img, 'Gaussian', 2);

But it is ok. In fact, in the following code, we can select a 'filter_type' without cal_W, thus this issue have no impact on the final result. Only when selecting filter_type as 'Nolocal_tensor' need we use 'cal_W'.
